# Travis doesn't support Rust, so we set it to Erlang, since we need escript
# anyway
language: erlang

otp_release:
   - 17.0

install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -

script:
  - cargo build --verbose
  - cargo test --verbose
  - escript examples/erlang_rust_port.erl
  - escript examples/json_port.erl
